# Row Echelon Form and Rank

In [1]:
import numpy as np

# Initializing matrix for test case a)
A1_square = np.array([[1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 3, 1], [0, 0, 3, 0]], dtype=np.float64)

# Initializing matrix for test case b)
A2_square = np.array([[0, 1, 1], [2, 6, 4], [1, 1, 4]], dtype=np.float64)

**Row echelon form for square matrices by Gaussian elimination**

In [2]:
def GE_square(A, print_flag):
    # Create a copy of the matrix to avoid modifying the original input
    R = A.copy()
    # Get the size (n x n) of the square matrix
    n = R.shape[0]
    # pvt_list will store the (row, col) indices of the pivots
    pvt_list = []
    # k is the current pivot column index
    k = 0
    # Define a small epsilon for floating-point comparisons (to handle near-zero numbers)
    eps = np.finfo(np.float32).eps

    # Iterate through each row (r is the current pivot row)
    for r in range(n):

        # --- Find Pivot Column ---
        # Find the next non-zero pivot column. 
        # This loop skips columns that are all-zero from row 'r' downwards.
        while k < n and np.allclose(R[r:, k], 0, atol=eps):
            k += 1
            # If we've run out of columns to check, the matrix is in row echelon form.
            if k == n:
                if print_flag:
                    print("Final R is:")
                    print(R)
                    print("Pivot List is: ", pvt_list)
                return R, pvt_list

        # --- Partial Pivoting (Row Swap) ---
        # Find the row index 'i' (at or below 'r') with the 
        # largest absolute value in the current pivot column 'k'.
        # This is for numerical stability.
        i = r + np.argmax(np.abs(R[r:, k]))
        # Swap the current row 'r' with the found pivot row 'i'
        R[[r, i], :] = R[[i, r], :]
        
        # Record the pivot's (row, col) index
        pvt_list.append([r, k])

        # --- Elimination ---
        # For every row 'j' below the current pivot row 'r'...
        for j in range(r + 1, n):
            # ...if the pivot element R[r, k] is not zero...
            if np.abs(R[r, k]) > eps:
                # ...subtract a multiple of the pivot row 'r' from row 'j'
                # to create a zero at R[j, k].
                R[j, :] = R[j, :] - ((R[j, k] / R[r, k]) * R[r, :])

        if print_flag:
            print("Current R after elimination:")
            print(R)
            print("Current pivot list is:", pvt_list)

    if print_flag:
        print("Final R is:")
        print(R)
        print("Current pivot list is:", pvt_list)

    return R, pvt_list

In [3]:
# Run Gaussian Elimination on A1_square with printing enabled
R, pvt_idx_list = GE_square(A1_square, True)

# print out the final row echelon form
print("\nrow echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R after elimination:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current pivot list is: [[0, 0]]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]
Current pivot list is: [[0, 0], [1, 2]]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Current pivot list is: [[0, 0], [1, 2], [2, 3]]
Final R is:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Pivot List is:  [[0, 0], [1, 2], [2, 3]]

row echelon form of A1_square:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0], [1, 2], [2, 3]]


In [4]:
# Run Gaussian Elimination on A2_square with printing enabled
R, pvt_idx_list = GE_square(A2_square, True)

# print out the final row echelon form
print("\nrow echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R after elimination:
[[ 2.  6.  4.]
 [ 0.  1.  1.]
 [ 0. -2.  2.]]
Current pivot list is: [[0, 0]]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list is: [[0, 0], [1, 1]]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list is: [[0, 0], [1, 1], [2, 2]]
Final R is:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current pivot list is: [[0, 0], [1, 1], [2, 2]]

row echelon form of A2_square:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]


**Row echelon form for rectangular matrices by Gaussian elimination**

In [13]:
# Initializing matrix for test case a) in Problem 1.2
A1_rect = np.array([[1, 2, 2, -1], [4, 8, 9, 6], [0, 3, 2, 9]], dtype=np.float64)

# Initializing matrix for test case b) in Problem 1.2
A2_rect = np.array([[1, 2, 3, 1, 2], [0, 4, 6, 0, 1], [2, 4, 8, 0, 0], [0, 1, 2, 0, 9]], dtype=np.float64)

In [14]:
import numpy as np

def GE_rectangular(A, print_flag):
    # Create a copy to avoid modifying the original
    R = A.copy()
    # Get the shape (n rows, m cols)
    n, m = R.shape
    # pvt_list will store the (row, col) indices of the pivots
    pvt_list = []
    # k is the current pivot column index
    k = 0
    # Define a small epsilon for floating-point comparisons
    eps = np.finfo(np.float32).eps

    # Iterate through each row (r is the current pivot row)
    for r in range(n):
        
        # --- Find Pivot Column ---
        # Find the next non-zero pivot column, checking up to 'm' columns.
        # This loop skips columns that are all-zero from row 'r' downwards.
        while k < m and np.all(np.abs(R[r:, k]) <= eps):
            k += 1
            # If we've run out of columns, the matrix is in row echelon form.
            if k == m:
                if print_flag:
                    print("Final R is:")
                    print(R)
                    print("Indices of pivot values:")
                    print(pvt_list)
                return R, pvt_list

        # --- Partial Pivoting (Row Swap) ---
        # Find the row index 'i' with the largest absolute value
        # in the current pivot column 'k' (for numerical stability).
        i = r + np.argmax(np.abs(R[r:, k]))
        # Swap the current row 'r' with the found pivot row 'i'
        R[[r, i], :] = R[[i, r], :]
        
        # Record the pivot's (row, col) index
        pvt_list.append([r, k])

        if print_flag:
            print("Current R:")
            print(R)
            print("Indices of pivot values:")
            print(pvt_list)

        # --- Elimination ---
        # For every row 'j' below the current pivot row 'r'...
        for j in range(r + 1, n):
            # ...if the pivot element R[r, k] is not zero...
            if np.abs(R[r, k]) > eps:
                # ...subtract a multiple of the pivot row 'r' from row 'j'
                # to create a zero at R[j, k].
                R[j, :] -= (R[j, k] / R[r, k]) * R[r, :]

        if print_flag:
            print("Current R after elimination:")
            print(R)
            print("Indices of pivot values:")
            print(pvt_list)

    if print_flag:
        print("Final R is:")
        print(R)
        print("Indices of pivot values:")
        print(pvt_list)

    return R, pvt_list

In [15]:
# Run Gaussian Elimination on A1_rect with printing enabled
R, pvt_idx_list = GE_rectangular(A1_rect, True)

# print out the final row echelon form
print("\nrow echelon form of A1_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R:
[[ 4.  8.  9.  6.]
 [ 1.  2.  2. -1.]
 [ 0.  3.  2.  9.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[ 4.    8.    9.    6.  ]
 [ 0.    0.   -0.25 -2.5 ]
 [ 0.    3.    2.    9.  ]]
Indices of pivot values:
[[0, 0]]
Current R:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R after elimination:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]
Current R after elimination:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]
Final R is:
[[ 4.    8.    9.    6.  ]
 [ 0.    3.    2.    9.  ]
 [ 0.    0.   -0.25 -2.5 ]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]

row echelon for

In [16]:
# Run Gaussian Elimination on A2_rect with printing enabled
R, pvt_idx_list = GE_rectangular(A2_rect, True)

# print out the final row echelon form
print("\nrow echelon form of A2_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R:
[[2. 4. 8. 0. 0.]
 [0. 4. 6. 0. 1.]
 [1. 2. 3. 1. 2.]
 [0. 1. 2. 0. 9.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[ 2.  4.  8.  0.  0.]
 [ 0.  4.  6.  0.  1.]
 [ 0.  0. -1.  1.  2.]
 [ 0.  1.  2.  0.  9.]]
Indices of pivot values:
[[0, 0]]
Current R:
[[ 2.  4.  8.  0.  0.]
 [ 0.  4.  6.  0.  1.]
 [ 0.  0. -1.  1.  2.]
 [ 0.  1.  2.  0.  9.]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R after elimination:
[[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.5   0.    8.75]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R:
[[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.5   0.    8.75]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]
Current R after elimination:
[[ 2.    4.    8.    0.    0.  ]
 [ 0.    4.    6.    0.    1.  ]
 [ 0.    0.   -1.    1.    2.  ]
 [ 0.    0.    0.    0.5   9.75]]
Indices of pivot val

In [17]:
# Test rectangular implementation on A1_square
R, pvt_idx_list = GE_rectangular(A1_square, True)
print("\nrow echelon form of A1_square:")
print(R)
print("Indices of pivot values:")
print(pvt_idx_list)

Current R:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Indices of pivot values:
[[0, 0]]
Current R:
[[1. 0. 1. 0.]
 [0. 0. 3. 1.]
 [0. 0. 0. 0.]
 [0. 0. 3. 0.]]
Indices of pivot values:
[[0, 0], [1, 2]]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]
Indices of pivot values:
[[0, 0], [1, 2]]
Current R:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0], [1, 2], [2, 3]]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0], [1, 2], [2, 3]]
Final R is:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0], [1, 2], [2, 3]]

row echelon form of A1_square:
[[ 1.  0.  1.  0.]
 [ 0.  0.  3.  1.]
 [ 0.

In [18]:
# Test rectangular implementation on A2_square
R, pvt_idx_list = GE_rectangular(A2_square, True)
print("\nrow echelon form of A2_square:")
print(R)
print("Indices of pivot values:")
print(pvt_idx_list)

Current R:
[[2. 6. 4.]
 [0. 1. 1.]
 [1. 1. 4.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0.  1.  1.]
 [ 0. -2.  2.]]
Indices of pivot values:
[[0, 0]]
Current R:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  1.  1.]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1]]
Current R:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]
Final R is:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]

row echelon form of A2_square:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[[0, 0], [1, 1], [2, 2]]


**Matrix rank and number of pivots**

In [19]:
# Define matrices X, Y, and Z
X = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 4]], dtype=np.float64)
Y = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
Z = np.array([[1, 2, 4, 1], [3, 5, 12, 3], [4, 8, 16, 6]], dtype=np.float64)

# Use GE_rectangular to find the row echelon form and pivots for each
print("--- Matrix X ---")
GE_rectangular(X, True)
print("\n--- Matrix Y ---")
GE_rectangular(Y, True)
print("\n--- Matrix Z ---")
R_Z, pvt_Z = GE_rectangular(Z, True)

--- Matrix X ---
Current R:
[[ 4.  8. 16.  4.]
 [ 3.  6. 12.  3.]
 [ 1.  2.  4.  1.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[ 4.  8. 16.  4.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0]]
Final R is:
[[ 4.  8. 16.  4.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Indices of pivot values:
[[0, 0]]

--- Matrix Y ---
Current R:
[[ 4.  8. 16.  6.]
 [ 3.  6. 12.  3.]
 [ 1.  2.  4.  1.]]
Indices of pivot values:
[[0, 0]]
Current R after elimination:
[[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.  -0.5]]
Indices of pivot values:
[[0, 0]]
Current R:
[[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.  -0.5]]
Indices of pivot values:
[[0, 0], [1, 3]]
Current R after elimination:
[[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.   0. ]]
Indices of pivot values:
[[0, 0], [1, 3]]
Final R is:
[[ 4.   8.  16.   6. ]
 [ 0.   0.   0.  -1.5]
 [ 0.   0.   0.   0. ]]
Indices of pivot values:
[[0, 0], [1, 3]]

--- Matrix Z

In [20]:
from numpy.linalg import matrix_rank

# Validate the ranks using numpy's built-in function
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)

print(f"Rank of X (NumPy): {r_X}")
print(f"Rank of Y (NumPy): {r_Y}")
print(f"Rank of Z (NumPy): {r_Z}")

Rank of X (NumPy): 1
Rank of Y (NumPy): 2
Rank of Z (NumPy): 3
